imports:
    - { resource: tables.yml }

services:
     lmdi.index.listener:
        class: lmdi\index\event\listener
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
        tags:
            - { name: event.listener }

     lmdi.index.controller:
        class: lmdi\index\controller\main
        arguments:
            - '@lmdi.index.core.edition'
            - '@lmdi.index.core.baledit'
            - '@lmdi.index.core.aiguillage'
            - '@lmdi.index.core.balises'
            - '@lmdi.index.core.balremp'
            - '@lmdi.index.core.ordre'
            - '@lmdi.index.core.famille'
            - '@template'
            - '@user'
            - '@language'
            - '@request'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'

     lmdi.index.core.edition:
        class: lmdi\index\core\edition
        arguments:
            - '@template'
            - '@user'
            - '@language'
            - '@dbal.conn'
            - '@cache'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%lmdi.index.tables.rh_tt%'
            - '%lmdi.index.tables.rh_t%'

     lmdi.index.core.baledit:
        class: lmdi\index\core\baledit
        arguments:
            - '@template'
            - '@language'
            - '@dbal.conn'
            - '@cache'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@ext.manager'
            - '@path_helper'
            - '@request'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%lmdi.index.tables.rh_tt%'
            - '%lmdi.index.tables.rh_t%'

     lmdi.index.core.balremp:
        class: lmdi\index\core\balremp
        arguments:
            - '@template'
            - '@language'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@ext.manager'
            - '@path_helper'
            - '@request'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%lmdi.index.tables.rh_tt%'
            - '%lmdi.index.tables.rh_t%'

     lmdi.index.core.aiguillage:
        class: lmdi\index\core\aiguillage
        arguments:
            - '@template'
            - '@language'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%lmdi.index.tables.rh_tt%'
            - '%lmdi.index.tables.rh_t%'

     lmdi.index.core.ordre:
        class: lmdi\index\core\ordre
        arguments:
            - '@template'
            - '@language'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%lmdi.index.tables.rh_tt%'
            - '%lmdi.index.tables.rh_t%'

     lmdi.index.core.famille:
        class: lmdi\index\core\famille
        arguments:
            - '@template'
            - '@language'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%lmdi.index.tables.rh_tt%'
            - '%lmdi.index.tables.rh_t%'

     lmdi.index.core.balises:
        class: lmdi\index\core\balises
        arguments:
            - '@template'
            - '@language'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%lmdi.index.tables.rh_tt%'
            - '%lmdi.index.tables.rh_t%'
